[pytest]
addopts = -v --html=reports/report.html --self-contained-html

# Show logs live in terminal during test execution.
log_cli = true

# Log level for terminal, here we can decide what level of logs we want in the console.
log_cli_level = INFO    

testpaths = tests
python_files = test_*.py